### ISSUE TITLE
Possible Problem with running on MacOS arm

### ISSUE THREAD

**Issue by qvalentin** [mrjosh/helm-ls#35]
After introducing tree-sitter cross compilation had to be reworked.
After this I encountered some problems on MacOS arm: helm-ls would get killed instantly after starting.
Can somebody verify this is a problem? @kforsthoevel maybe?

While the problem persists you can just use the amd64 version on MacOS arm which is working.

**Comment by kforsthoevel** [comment]
Yes, I can conform that it's crashing instantly after starting on Mac OS w/ ARM.

```
[START][2023-06-05 14:22:02] LSP logging initiated
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	'{"level":"info","msg":"helm-lint-langserver: connections opened","time":"2023-06-05T14:22:02+02:00"}\n'
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	'panic: failed to parse request URI: parse "": empty url\n\ngoroutine 8 [running]:\n'
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"go.lsp.dev/uri.URI.Filename(...)\n\t/home/runner/go/pkg/mod/go.lsp.dev/uri@v0.3.0/uri.go"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	":52\ngithub.com/mrjosh/helm-ls/internal/handler.(*langHandler).handleInitialize(0x14000093ce0, {0x105b2d440, 0x14000134008}, 0x140001ca150, {0x12d88ff98, 0x14000459e80})\n\t"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"/home/runner/work/helm-ls/helm-ls/internal/handler/handler.go:72 +0x260\n"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"github.com/mrjosh/helm-ls/internal/handler.(*langHandler).handle(0x14000093ce0, "
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"{0x105b2d440, 0x14000134008}, 0x140001ca150, {0x12d88ff98?, 0x14000459e80?})\n\t/home/runner/work/helm-ls/helm-ls/internal/handler/handler.go:43 +0x17c\n"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"go.lsp.dev/jsonrpc2.ReplyHandler.func1({0x105b2d440, 0x14000134008}, 0x1400011e600, {0x12d88ff98?, 0x14000459e80?})\n\t/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xf4\ngo.lsp.dev/jsonrpc2.(*conn).run(0x1400047f130, {0x105b2d440, 0x14000134008}, 0x14000091710)\n\t/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/conn.go:206 +0x258\n"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"created by go.lsp.dev/jsonrpc2.(*conn).Go\n\t"
[ERROR][2023-06-05 14:22:02] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/local/bin/helm_ls"	"stderr"	"/home/runner/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/conn.go:189 +0xb0\n"
```

**Comment by kforsthoevel** [comment]
Unfortunately, it's not working with an older version.

**Comment by kforsthoevel** [comment]
@qvalentin I have found out what has caused the error about the empty filename. I was using `helm_ls` with [helmfile](https://github.com/helmfile/helmfile) which have no `Chart.yaml`.

Now I can confirm that the ARM version isn't working but the AMD version is working on Mac ARM.

**Comment by qvalentin** [comment]
Ok, what is the output if you try to run 
`helm_ls --version`? Does the process get killed?

**Comment by mrjosh** [comment]
Please use the amd64 version of helm_ls on macOS till this issue get fixed! Im closing this issue

**Comment by qvalentin** [comment]
We should try goreleaser instead of xgo:  https://github.com/goreleaser/goreleaser-cross

**Comment by mrjosh** [comment]
> We should try goreleaser instead of xgo: https://github.com/goreleaser/goreleaser-cross

I'll look into it
