### ISSUE TITLE
Helm_ls still failing when no values.yml exist

### ISSUE THREAD

**Issue by JohannesE-MW** [mrjosh/helm-ls#48]
Hello there, 

we are deploying Helm charts via ArgoCD, so there is no values.yml below the template folder needed. While the change in #43 should fix that, it still fails for me on MacOS with ARM:

```
[START][2023-10-31 12:13:41] LSP logging initiated
[ERROR][2023-10-31 12:13:41] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/johannes.e/.local/share/nvim/mason/bin/helm_ls"   "stderr" '{"level":"info","msg":"helm-lint-langserver: connections opened","time":"2023-10-31T12:13:41+01:00"}\n{"level":"info","msg":"Error loading values.yaml file open /Users/johannes.e/repos/deployment/applications/services/values.yml: no such file or directory","time":"2023-10-31T12:13:41+01:00"}\n'
[ERROR][2023-10-31 12:13:41] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/johannes.e/.local/share/nvim/mason/bin/helm_ls"   "stderr" 'panic: request "initialize" was never replied to\n\ngoroutine 36 [running]:\n'
[ERROR][2023-10-31 12:13:41] .../vim/lsp/rpc.lua:734    "rpc"   "/Users/johannes.e/.local/share/nvim/mason/bin/helm_ls"   "stderr" "go.lsp.dev/jsonrpc2.ReplyHandler.func1({0x10416ea58, 0x140000420e8}, 0x140004b7300, {0x12c62c858?, 0x14000428b80?})\n\tgo.lsp.dev/jsonrpc2@v0.10.0/handler.go:44 +0x158\ngo.lsp.dev/jsonrpc2.(*conn).run(0x140004a9a40, {0x10416ea58, 0x140000420e8}, 0x140004b9d10)\n\tgo.lsp.dev/jsonrpc2@v0.10.0/conn.go:206 +0x234\ncreated by go.lsp.dev/jsonrpc2.(*conn).Go\n\tgo.lsp.dev/jsonrpc2@v0.10.0/conn.go:189 +0xac\n"
```

Neovim only shows: `Client 2 quit with exit code 2 and signal 0`.

Mason installed the latest version:

```
/Users/johannes.e/.local/share/nvim/mason/bin/helm_ls version
HelmLs version: e534e0e
Build type: Nightly
Build time: 2023-09-30_12:30:33PM
Golang: go1.20.6
Compiled by: fv-az407-100
```

When I create an empty values.yml it works.

Can this be fixed?

BR,

Johannes

**Comment by qvalentin** [comment]
Sorry, my bad: Should have tested it better.
