### ISSUE TITLE
helm-ls newer than v0.0.9, and nvim-lspconfig throws unimplemented panic.

### ISSUE THREAD

**Issue by madelaney** [mrjosh/helm-ls#73]
When using nvim (v0.9.5), and nvim-lspconfig (e25c4cd), and helm-ls (v0.0.14; really anything newer then v0.0.10), when I start the LSP server, I get the following error messages:

```console
[START][2024-04-10 09:12:15] LSP logging initiated
[ERROR][2024-04-10 09:12:15] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/mdelaney/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"info","msg":"helm-lint-langserver: connections opened","time":"2024-04-10T09:12:15-04:00"}\n'
[ERROR][2024-04-10 09:12:15] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/mdelaney/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"info","msg":"Workspace configuration: {{true yaml-language-server 50 false {map[kubernetes:templates/**] true true {true https://www.schemastore.org/api/json/catalog.json}}} {values.yaml values.lint.yaml values*.yaml} info}","time":"2024-04-10T09:12:15-04:00"}\n'
[ERROR][2024-04-10 09:12:15] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/mdelaney/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"info","msg":"helm lint: result for file file:///Users/mdelaney/work/<workspace>/stackgres-cluster/templates/sgcluster.yaml : []","time":"2024-04-10T09:12:15-04:00"}\n'
[ERROR][2024-04-10 09:12:15] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/mdelaney/.local/share/nvim/mason/bin/helm_ls"	"stderr"	"panic: unimplemented\n\ngoroutine 14 [running]:\ngithub.com/mrjosh/helm-ls/internal/handler.(*langHandler).Request(0x1400044a01a?, {0x140000bd830?, 0x1060346e8?}"
[ERROR][2024-04-10 09:12:15] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/mdelaney/.local/share/nvim/mason/bin/helm_ls"	"stderr"	", {0x105d95700?, 0x14000286010?}, {0x10df8ef98?, 0x140004d5cb0?})\n\tgithub.com/mrjosh/helm-ls/internal/handler/handler.go:208 +0x2c\ngo.lsp.dev/protocol.NewServer.ServerHandler.func1({0x106022548, 0x140000bd830}, 0x1400057c000, {0x10df8ef98, 0x140004d5cb0})\n\tgo.lsp.dev/protocol@v0.12.0/server.go:49 +0x124\ngo.lsp.dev/protocol.Handlers.ReplyHandler.func1({0x106022548, 0x140000bd830}, 0x140000c6798, {0x10df8ef98?, 0x140004d5cb0?})\n\tgo.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xdc\ngo.lsp.dev/protocol.Handlers.AsyncHandler.func2.2()\n\tgo.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x78\ncreated by go.lsp.dev/protocol.Handlers.AsyncHandler.func2 in goroutine 10\n\tgo.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x194\n"
```

I do have a values.yaml file, but I don't have any values.lint.yaml or additional values*.yaml files.

I figured this is part of v0.0.10, specifically the commit https://github.com/mrjosh/helm-ls/commit/46c5f65eaad11a2f89d1dd8fa7e63590294b8884.

If I downgrade to v0.0.9 (via 'MasonInstall helm-ls@v0.0.9'), then everything works just fine.

**Comment by qvalentin** [comment]
Hi, thanks for reporting. I don't know why your client calls the Request method and mine did not, but the lsp should not panic anyway. I will release a fix asap.

The log you posted does not match v0.0.10, are you sure that this version also has the same bug?

**Comment by madelaney** [comment]
> The log you posted does not match v0.0.10, are you sure that this version also has the same bug?

It's possible that it was 0.0.14, not 0.0.10; my apologies, I was jumping around versions and I could have grabbed the wrong lines.

**Comment by madelaney** [comment]
To close the loop on this.

I installed v0.0.15 via Mason, and the issue has gone away.
