### ISSUE TITLE
helm_ls quit with exit code 2 and signal 0

### ISSUE THREAD

**Issue by liukango** [mrjosh/helm-ls#87]
I have a helmfile project with files like this:

```
helmfile-project
├── environments
│   ├── ops
│   │   └── k8s-ops.yaml
│   ├── prd
│   │   ├── k8s-prd-1.yaml
│   │   └── k8s-prd-2.yaml
│   └── stg
│       └── k8s-stg-1.yaml
└── releases
    ├── helmfile.yaml
    ├── release1
    │   ├── helmfile.yaml
    │   └── values.yaml.gotmpl
    └── release2
        ├── helmfile.yaml
        └── values.yaml.gotmpl
```

When I open `*.yaml` files, it's OK. But if I open `*.yaml.gotmpl` files, warning appears:

```
Client helm_ls quit with exit code 2 and signal 0.
```

And if I check the log, it's like this:

```
[ERROR][2024-05-21 00:16:03] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/****/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"info","msg":"helm-lint-langserver: connections opened","time":"2024-05-21T00:16:03+08:00"}\n'
[ERROR][2024-05-21 00:16:03] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/****/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"error","msg":"length WorkspaceFolders is 0, falling back to current working directory","time":"2024-05-21T00:16:03+08:00"}\n'
[ERROR][2024-05-21 00:16:03] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/****/.local/share/nvim/mason/bin/helm_ls"	"stderr"	"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x2 addr="
[ERROR][2024-05-21 00:16:03] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/****/.local/share/nvim/mason/bin/helm_ls"	"stderr"	"0x20 pc=0x1053acc20]\n\ngoroutine 52 [running]:\ngithub.com/mrjosh/helm-ls/internal/handler.(*langHandler).LoadDocsOnNewChart.func1({0x140000581e0, 0x48}, {0x0?, 0x0?}, {0x140000581e0?, 0x48?})\n\tgithub.com/mrjosh/helm-ls/internal/handler/text_document.go:109 +0x30\npath/filepath.WalkDir({0x140000581e0, 0x48}, 0x14000509768)\n\tpath/filepath/path.go:530 +0x50\ngithub.com/mrjosh/helm-ls/internal/handler.(*langHandler).LoadDocsOnNewChart("
[ERROR][2024-05-21 00:16:03] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/****/.local/share/nvim/mason/bin/helm_ls"	"stderr"	"0x140001e2180, {0x1400017eeb0?, 0x140004262b0?})\n\tgithub.com/mrjosh/helm-ls/internal/handler/text_document.go:107 +0x84\ncreated by github.com/mrjosh/helm-ls/internal/handler.(*langHandler).NewChartWithInitActions in goroutine 10\n\tgithub.com/mrjosh/helm-ls/internal/handler/initialization.go:88 +0xa8\n"
```

Is there something I mis-configured, or is this a bug?

Thanks!

**Comment by qvalentin** [comment]
Yes, this is a bug, the panic should be fixed in https://github.com/mrjosh/helm-ls/pull/80.
The problem is the missing `templates` directory.

Either way helmfile projects are currently not really supported (see https://github.com/mrjosh/helm-ls/issues/27).

**Comment by liukango** [comment]
@qvalentin Thanks for your information!
